services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - MODEL_RUN_ID=1ca05c6d23f44066a4a4dcdbe1639de4
      - AWS_DEFAULT_REGION=us-east-1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
      - AWS_ACCESS_KEY_ID="aws_id_123"
      - AWS_SECRET_ACCESS_KEY="aws_key_123"
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
